 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: hello-worl-ingress
   namespace: app-1
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - http:
       paths:
       - path: /app
         backend:
           serviceName: hello-svc
           servicePort: 8080